[package]
name = "spina"
version = "0.1.0"
edition = "2024"

[[bin]]
path = "crates/core/main.rs"
name = "spina"

[workspace]
members = [
    "crates/bc",
    "crates/lex",
    "crates/parser",
    "crates/common"
]

[dependencies]
anyhow = "^1.0.104"
bc = {path = "crates/bc"}
lex = {path = "crates/lex"}
parser = {path = "crates/parser"}

[workspace.dependencies]
common = {path = "crates/common"}
thiserror = "^2"
